(() => {
    const $ = id => document.getElementById(id), roles = { owner: '数据拥有者', user: '数据用户', cloud: '云服务器', curator: 'Key Curator' }, letters = { owner: 'A', cloud: 'B', user: 'C', curator: 'D' };
    let state = null, selected = null, dock = 'messages', busy = false, timer = null, lastMessages = '', lastSamples = '', lastVehicles = '', csrf = '';
    let inbox = [], inboxVehicle = null, selectionVersion = 0, inboxRequest = 0;
    const reasons = { NOT_REGISTERED_AT_ENCRYPTION: '该车辆在此密文生成之后才注册，不能解密历史密文。', RECEIVER_POLICY: '访问被拒绝：当前车辆不满足发送方的访问策略。', SENDER_POLICY: '访问被拒绝：发送方不满足你指定的验证策略。', SENDER_VERIFICATION: '发送方配对验证未通过。', REVOKED: '当前车辆已被撤销：C 本地解密后的完整性校验失败。', INTEGRITY: '本地完整性校验失败，密文或密钥不匹配。' };
    function el(tag, text, className) { let e = document.createElement(tag); if (text !== undefined) e.textContent = text; if (className) e.className = className; return e; }
    function toast(text, error = false) { $('toast').textContent = text; $('toast').className = 'toast' + (error ? ' error' : ''); clearTimeout(timer); timer = setTimeout(() => $('toast').classList.add('hidden'), 6000); }
    function result(text, error = false) { $('result-box').textContent = text; $('result-box').className = 'result-box' + (error ? ' error' : ''); }
    function options(select, items) { const old = select.value; select.replaceChildren(); if (!items.length) { select.append(el('option', '暂无可用记录')); select.options[0].value = ''; } for (let [value, label] of items) { let o = el('option', label); o.value = value; select.append(o); } if (items.some(x => String(x[0]) === old)) select.value = old; }
    function selectedCar() { return state?.vehicles?.find(v => v.id === selected); }
    window.selectVehicle = id => { selectionVersion++; inboxRequest++; inbox=[]; inboxVehicle=null; $('result-box').textContent=''; $('result-box').classList.add('hidden'); selected = Number(id); City.select(selected); $('vehicle-select').value = String(id); renderVehicle(); Cockpit.select(selectedCar(), true); renderDock(); loadInbox(); };
    function attributeItems(v) { const values = Array.isArray(v?.attributes) ? v.attributes : v?.attributes && typeof v.attributes === 'object' ? Object.values(v.attributes) : []; return values.map(value => { const raw = String(value); const n = typeof value === 'number' ? value : /^A?\d+$/i.test(raw) ? Number(raw.replace(/^A/i, '')) - 1 : NaN; const code = Number.isInteger(n) && n >= 0 ? 'A' + (n + 1) : raw; const name = Number.isInteger(n) && n >= 0 ? state?.attributeNames?.[code] : ''; return { code, text: code + (name ? ' ' + name : '') }; }); }
    function renderVehicle() { let v = selectedCar(); if (!v) return; const attrs = attributeItems(v); $('selected-number').textContent = v.number; $('selected-description').textContent = (v.role === 'owner' ? '拥有者车辆 · 私钥位于 A' : '数据用户车辆 · 私钥位于 C'); $('selected-role').textContent = v.leaked ? '密钥泄露' : roles[v.role]; $('selected-status').textContent = !v.registered ? '已注销' : v.leaked ? '存在泄露样本' : '已注册'; $('attribute-count').textContent = attrs.length + ' 个'; $('attributes').replaceChildren(...attrs.map(a => el('span', a.text))); $('attributes').setAttribute('aria-label', attrs.map(a => a.text).join('、')); const entry = $('enter-cockpit'); if (entry) { const canEnter = state?.role !== 'cloud' && v.role === state?.role; entry.disabled = !canEnter; entry.textContent = canEnter ? '进入车内' : '仅本端车辆可用'; } $('car-illustration').style.setProperty('--car-color', v.leaked ? '#c77969' : v.role === 'owner' ? '#e79950' : '#70a69a'); updateButtons(); }
    function updateButtons() { if (!state) return; let ready = state.ready && state.localReady && !busy && !state.connectionError, v = selectedCar(); $('send-button').disabled = !v?.registered || !ready || state.role !== 'owner' || v?.role !== 'owner'; $('decrypt-button').disabled = !v?.registered || !ready || state.role !== 'user' || v?.role !== 'user' || !$('receive-message').value; $('revoke-button').disabled = !ready || state.role !== 'owner' || !v || !$('revoke-message').value; $('leak-button').disabled = !ready || state.role !== 'user' || v?.role !== 'user'; $('trace-button').disabled = state.role === 'curator' || !ready || !$('sample-select').value; const pending=(state.jobs||[]).filter(j=>j.status!=='done').length; const registerReason=busy?'正在处理操作，请稍候':state.role!=='curator'?'请在 D 端注册车辆':!state.localReady?(state.error||state.localError?'初始化失败：'+(state.error||state.localError):'公共参数准备中：'+(state.localPhase||state.phase||'初始化中')+'。完成后自动开放注册，请保持 D 端运行。'):state.ctr+pending>=state.capacity?'注册名额已用完（含排队任务）；已注销车辆可使用重新加入。':''; $('register-button').disabled=!!registerReason; $('register-button').title=registerReason; $('register-status').textContent=registerReason||'D 端已就绪。输入属性名称，以逗号分隔，例如：特斯拉,运营。'; $('deregister-button').textContent='注销当前车辆'+(v?' · '+v.number:''); $('deregister-button').disabled=busy || state.role!=='curator' || !state.localReady || !v?.registered; $('rejoin-button').disabled=busy || state.role!=='curator' || !state.localReady || !v || v.registered; $('pause').disabled=state.role==='curator'; }
    function tab(name) { if(state?.role==='curator')name='registry'; document.querySelectorAll('[data-tab]').forEach(b => b.classList.toggle('active', b.dataset.tab === name)); document.querySelectorAll('.tab-pane').forEach(e => e.classList.toggle('hidden', e.id !== 'tab-' + name)); $('result-box').classList.add('hidden'); }
    function renderDock() {
        if (!state) return; const content = $('dock-content'); content.replaceChildren(); $('dock-subtitle').textContent = { messages: 'ENCRYPTED DATA STREAM', events: 'LIVE EXPERIMENT EVENTS', inbox: 'LOCAL DECRYPTED MESSAGES' }[dock];
        if (dock === 'messages') { const messages = [...(state.messages || [])].reverse(); if (!messages.length) { content.append(el('div', '等待第一条加密消息。选择拥有者车辆，开始共享。', 'empty-state')); return; } for (const m of messages) { const c = el('button', undefined, 'message-card'), head = el('div', undefined, 'card-top'); head.append(el('span', '◈ ' + m.id), el('span', 'v' + m.version + ' · ' + m.bytes + ' B', 'encrypted-badge')); c.append(head, el('b', m.title), el('code', m.policy + '  /  ' + m.preview.slice(0, 15) + '…')); c.onclick = () => { $('receive-message').value = m.id; $('revoke-message').value = m.id; tab('share'); updateVersions(); updateButtons(); toast('已选择密文 ' + m.id); }; content.append(c); } }
        else if (dock === 'events') { let list = el('div', undefined, 'event-list'); for (let e of [...state.events].reverse().slice(0, 30)) { let row = el('div', undefined, 'event-row ' + e.type); row.append(el('time', new Date(e.at).toLocaleTimeString('zh-CN', { hour12: false })), el('i'), el('span', e.text)); list.append(row); } content.append(list); }
        else { if (state.role !== 'user' || selectedCar()?.role !== 'user') { content.append(el('div', '明文仅存在于 C 端，本节点不接收解密结果。', 'empty-state')); return; } if (inboxVehicle !== selected || !inbox.length) { content.append(el('div', '当前车辆暂无本地解密记录。只有此车辆解密成功后，明文才会显示在这里。', 'empty-state')); return; } for (let m of inbox) { let card = el('div', undefined, 'inbox-card'); card.append(el('b', m.id + ' · V-' + String(m.receiver + 1).padStart(3, '0') + ' · 版本 ' + m.version), el('p', m.text)); content.append(card); } }
    }
    function updateVersions() { let m = state?.messages.find(x => x.id === $('revoke-message').value); $('version-info').textContent = m ? '当前版本：v' + m.version + '\n已撤销车辆：' + (m.revoked.length ? m.revoked.map(i => 'V-' + String(i + 1).padStart(3, '0')).join('、') : '无') : '暂无云端密文'; }
    function render() {
        City.update(state.vehicles || []); Cockpit.configure(state.role, state.vehicles || []); $('count-messages').textContent = state.messages?.length || 0; $('count-revoked').textContent = (state.messages || []).reduce((sum, m) => sum + m.revoked.length, 0); $('count-leaks').textContent = state.samples?.length || 0; $('dock-count').textContent = state.messages?.length || 0; $('role-pill').textContent = '电脑 ' + letters[state.role] + ' · ' + roles[state.role]; $('world-state').textContent = state.connectionError ? '云端连接中断' : state.phase || '等待初始化'; $('local-status').textContent = state.localError || state.localPhase || state.phase || '连接中'; for (let r of ['owner', 'cloud', 'user', 'curator']) $('node-' + r).classList.toggle('online', !!state.nodes?.[r]);
        const isCurator=state.role==='curator'; document.body.classList.toggle('curator-mode',isCurator); document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('hidden',isCurator?b.dataset.tab!=='registry':b.dataset.tab==='registry')); if(isCurator) { tab('registry'); if(dock!=='events')dock='events'; document.querySelectorAll('[data-dock]').forEach(b=>b.classList.toggle('active',b.dataset.dock==='events')); }
        $('attribute-dictionary').replaceChildren(...Array.from({length:state.universe||50},(_,i)=>{const code='A'+(i+1);return el('span',code+'：'+(state.attributeNames?.[code]||'未分配'));}));
        $('registration-jobs').replaceChildren(...(state.jobs||[]).slice(-6).reverse().map(j=>el('div',j.name+' · '+(j.status==='done'?'注册成功 V-'+String(j.vehicle+1).padStart(3,'0'):'排队等待 '+letters[j.role]+' 本机生成密钥'))));
        $('inbox-tab').classList.toggle('hidden',state.role!=='user');
        $('owner-form').classList.toggle('hidden', state.role !== 'owner'); $('user-form').classList.toggle('hidden', state.role !== 'user'); $('cloud-form').classList.toggle('hidden', state.role !== 'cloud'); $('revoke-hint').textContent = state.role === 'owner' ? 'A 生成 UK / PI，B 同时验证并更新 C₄ 与辅助密钥。' : '请在电脑 A 选择目标车辆并提交撤销授权。';
        const vs = JSON.stringify(state.vehicles); if (vs !== lastVehicles) { lastVehicles = vs; options($('vehicle-select'), (state.vehicles || []).map(v => [v.id, v.number + ' · ' + roles[v.role] + (!v.registered ? ' · 已注销' : v.leaked ? ' · 泄露' : '')])); if (selected === null && state.vehicles?.length) selected = (state.vehicles.find(v => v.role === state.role) || state.vehicles[0]).id; if (selected !== null) { $('vehicle-select').value = selected; City.select(selected); renderVehicle(); } }
        Cockpit.select(selectedCar());
        const ms = JSON.stringify(state.messages); if (ms !== lastMessages) { lastMessages = ms; const items = [...(state.messages || [])].reverse().map(m => [m.id, m.id + ' · ' + m.title + ' · v' + m.version]); options($('receive-message'), items); options($('revoke-message'), items); updateVersions(); }
        const ss = JSON.stringify(state.samples); if (ss !== lastSamples) { lastSamples = ss; options($('sample-select'), [...(state.samples || [])].reverse().map(s => [s.id, s.id + (s.traced !== null ? ' · 已识别 i′=' + (s.traced + 1) : ' · 待追踪')])); } renderDock(); updateButtons();
    }
    async function loadInbox() { const id=selected, version=selectionVersion, request=++inboxRequest; if(state?.role!=='user'||selectedCar()?.role!=='user'){inbox=[];inboxVehicle=null;renderDock();return;} try{const res=await fetch('/api/inbox?vehicle='+id);if(!res.ok)throw new Error('收件箱不可用');const data=await res.json();if(selected===id&&selectionVersion===version&&request===inboxRequest){inbox=data.inbox;inboxVehicle=data.vehicle;renderDock();}}catch(e){if(selected===id&&request===inboxRequest){inbox=[];inboxVehicle=null;renderDock();}} }
    async function syncMotion(){const start=performance.now();try{const res=await fetch('/api/motion');if(res.ok)City.sync(await res.json(),performance.now()-start);}catch(e){}finally{setTimeout(syncMotion,1000);}}
    window.setCityPaused=async paused=>{try{const data=await api('motion/set',{paused});City.sync(data);toast(paused?'全城暂停':'全城继续行驶');}catch(e){toast(e.message,true);}};
    async function poll() { try { const res = await fetch('/api/state'); if (!res.ok) throw new Error('HTTP ' + res.status); state = await res.json(); csrf = state.csrf; render(); loadInbox(); } catch (e) { $('world-state').textContent = '节点连接失败'; $('local-status').textContent = e.message; } finally { setTimeout(poll, 2300); } }
    async function api(path, body) { let res; try { res = await fetch('/api/' + path, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Local-Token': csrf }, body: JSON.stringify(body) }); } catch (e) { throw new Error('与本机服务的连接中断。请确认服务仍在运行；刷新页面检查任务是否已提交，再决定是否重试。'); } const data = await res.json(); if (!res.ok) throw new Error(data.error || '操作失败'); return data; }
    async function action(fn) { if (busy) return; const actingVehicle = selected; busy = true; updateButtons(); try { await fn(); const res = await fetch('/api/state'); state = await res.json(); render(); } catch (e) { result(e.message, true); toast(e.message, true); Cockpit.status(actingVehicle, '操作未完成，请查看右侧', 'error'); $('pipeline').classList.add('hidden'); } finally { busy = false; updateButtons(); } }
    function pipeline(a, b, c) { $('pipeline').classList.remove('hidden');['a', 'b', 'c'].forEach((k, i) => $('pipe-' + k).className = [a, b, c][i] || ''); }
    $('send-button').onclick = () => action(async () => { const vehicleId = selected; Cockpit.status(vehicleId, '正在加密并上传…', 'working'); pipeline('running', '', ''); let data = await api('send', { sender: selected, text: $('message-text').value, policy: $('send-policy').value, title: '城市路况共享' }); pipeline('done', 'done', ''); Cockpit.status(vehicleId, '密文已上传', 'success'); result('密文 ' + data.id + ' 已上传至 B\n策略：' + data.policy + '\nA 端加密：' + Number(data.encryptMs).toFixed(2) + ' ms\n请在 C 选择用户车辆并请求解密。'); toast('已加密并发送，云端只收到密文'); setTimeout(() => $('pipeline').classList.add('hidden'), 6000); });
    $('decrypt-button').onclick = () => action(async () => { const vehicleId = selected, version=selectionVersion; Cockpit.status(vehicleId, '云端转换 · 本地解密…', 'working'); pipeline('done', 'running', ''); let data = await api('decrypt', { id: $('receive-message').value, receiver: selected, reverse: $('reverse-policy').value }); if(selected!==vehicleId || selectionVersion!==version){toast('V-'+String(vehicleId+1).padStart(3,'0')+' 操作完成，请切回该车辆查看结果');return;} if (data.ok) { Cockpit.status(vehicleId, '本地解密成功', 'success'); pipeline('done', 'done', 'done'); result('本地解密成功 · 版本 ' + data.version + '\n\n' + data.text + '\n\nB 转换 ' + Number(data.transformMs).toFixed(2) + ' ms · C 解密 ' + Number(data.decryptMs).toFixed(2) + ' ms'); toast('双向访问通过，文字已在 C 本地恢复'); dock = 'inbox'; await loadInbox(); document.querySelectorAll('[data-dock]').forEach(b => b.classList.toggle('active', b.dataset.dock === dock)); } else { Cockpit.status(vehicleId, data.reason === 'REVOKED' ? '访问权限已撤销' : '访问验证未通过', 'error'); pipeline('done', data.reason === 'REVOKED' || data.reason === 'INTEGRITY' ? 'done' : 'failed', 'failed'); result(reasons[data.reason] || '访问被拒绝', true); toast(reasons[data.reason] || '访问被拒绝', true); } setTimeout(() => $('pipeline').classList.add('hidden'), 6500); });
    $('revoke-button').onclick = () => action(async () => { let data = await api('revoke', { id: $('revoke-message').value, target: selected }); result('撤销更新成功 · 密文版本 v' + data.version + '\nUK / PI 的配对校验已通过。\n请在 C 使用当前车辆再次解密，验证撤销效果。\n总耗时 ' + Number(data.totalMs).toFixed(2) + ' ms'); toast('当前车辆已被指定密文撤销'); });
    $('leak-button').onclick = () => action(async () => { let data = await api('leak', { source: selected }); result('泄露样本 ' + data.id + ' 已创建。\n该样本来自 C 本机实际私钥的复制，可交由 B 追踪。'); toast('实际私钥复制样本已提交'); });
    $('trace-button').onclick = () => action(async () => { let data = await api('trace', { sample: $('sample-select').value }); $('trace-result').replaceChildren(el('span', '已识别注册身份'), el('strong', 'i′ = ' + data.identity), ...data.checks.map(c => el('div', '✓ ' + c))); result('Trace 验证通过\n车辆 V-' + String(data.identity).padStart(3, '0') + '\n耗时 ' + Number(data.traceMs).toFixed(2) + ' ms'); window.selectVehicle(data.slot); City.focus(data.slot); toast('追踪成功：注册身份 i′ = ' + data.identity); });
    $('register-button').onclick=()=>action(async()=>{const attributeNames=$('new-attrs').value.split(/[,，\n]+/).map(x=>x.trim()).filter(Boolean);if(!attributeNames.length)throw new Error('请至少输入一个属性名称');const r=await api('register',{name:$('new-name').value,role:$('new-role').value,attributeNames});result(r.message);toast('注册任务已提交 D');});
    $('rejoin-button').onclick=()=>action(async()=>{const r=await api('rejoin',{vehicle:selected});result(r.message);toast('车辆已重新加入系统');});
    $('deregister-button').onclick=()=>action(async()=>{const r=await api('deregister',{vehicle:selected});result(r.message+'\n已注销 V-'+String(r.vehicle+1).padStart(3,'0'));toast('车辆已注销');});
    $('vehicle-select').onchange = e => window.selectVehicle(e.target.value); $('focus-car').onclick = () => { const v = selectedCar(); if (v && v.role === state.role && state.role !== 'cloud') Cockpit.select(v, true); else City.focus(selected); }; $('enter-cockpit').onclick = () => { const v = selectedCar(); if (v && v.role === state?.role && state.role !== 'cloud') Cockpit.select(v, true); }; $('receive-message').onchange = updateButtons; $('revoke-message').onchange = () => { updateVersions(); updateButtons(); }; $('sample-select').onchange = updateButtons;
    document.querySelectorAll('[data-tab]').forEach(b => b.onclick = () => tab(b.dataset.tab)); document.querySelectorAll('[data-policy]').forEach(b => b.onclick = () => $('send-policy').value = b.dataset.policy); document.querySelectorAll('[data-dock]').forEach(b => b.onclick = () => { dock = b.dataset.dock; document.querySelectorAll('[data-dock]').forEach(t => t.classList.toggle('active', t === b)); renderDock(); });
    $('help-button').onclick = () => $('help-dialog').showModal(); $('close-help').onclick = $('start-guide').onclick = () => $('help-dialog').close(); poll(); syncMotion();
})();
